<?php get_header(); ?>
<?php
$type=isset($_GET['type'])?sanitize_key(wp_unslash($_GET['type'])):'all';$query_text=get_search_query();$school_terms=array();$normalized_query=$query_text?(function_exists('yl_normalize_search_text')?yl_normalize_search_text($query_text):strtolower(remove_accents($query_text))):'';
if(in_array($type,array('all','school'),true)&&$query_text){$all_terms=get_terms(array('taxonomy'=>'near_school','hide_empty'=>false));if(!is_wp_error($all_terms)){foreach($all_terms as $t){$hay=$t->name.' '.yl_get_school_meta($t,'short_name').' '.yl_get_school_meta($t,'aliases');$normalized_hay=function_exists('yl_normalize_search_text')?yl_normalize_search_text($hay):strtolower(remove_accents($hay));if(''!==$normalized_query&&false!==strpos($normalized_hay,$normalized_query))$school_terms[]=$t;}}}
$place_result_count=('school'===$type)?0:(int)$GLOBALS['wp_query']->found_posts;$total_visible=$place_result_count+count($school_terms);
?>
<div class="yl-page-shell"><div class="yl-container"><header class="yl-page-header"><p class="yl-eyebrow">Tìm kiếm</p><h1><?php echo $query_text?'Kết quả cho “'.esc_html($query_text).'”':'Tìm trên YangLocal'; ?></h1><?php if($query_text): ?><p class="yl-search-count"><?php echo esc_html(number_format_i18n($total_visible).' kết quả'); ?></p><?php endif; ?><form class="yl-search-form" role="search" method="get" action="<?php echo esc_url(home_url('/')); ?>"><label class="screen-reader-text" for="yl-search-page-input">Từ khóa tìm kiếm</label><input id="yl-search-page-input" type="search" name="s" value="<?php echo esc_attr($query_text); ?>" placeholder="Tên địa điểm, trường, bài viết…" required><input type="hidden" name="type" value="<?php echo esc_attr($type); ?>"><button class="yl-button" type="submit">Tìm kiếm</button></form></header>
<?php $tabs=array('all'=>'Tất cả','place'=>'Địa điểm','school'=>'Trường','article'=>'Bài viết','event'=>'Sự kiện'); ?><div class="yl-search-tabs"><?php foreach($tabs as $key=>$label): ?><a class="<?php echo $type===$key?'is-active':''; ?>" href="<?php echo esc_url(add_query_arg(array('s'=>$query_text,'type'=>$key),home_url('/'))); ?>"><?php echo esc_html($label); ?></a><?php endforeach; ?></div>
<?php if($school_terms): ?><section class="yl-search-schools"><div class="yl-section-heading yl-section-heading--compact"><div><p class="yl-eyebrow">Campus</p><h2>Trường phù hợp</h2></div></div><div class="yl-school-index-grid"><?php foreach(array_slice($school_terms,0,8) as $term): ?><a class="yl-school-index-card" href="<?php echo esc_url(get_term_link($term)); ?>"><span class="yl-eyebrow"><?php echo esc_html(yl_get_school_meta($term,'short_name',$term->name)); ?></span><strong><?php echo esc_html($term->name); ?></strong><small><?php echo esc_html(yl_get_school_meta($term,'district','Hà Nội')); ?> · Xem quanh trường</small></a><?php endforeach; ?></div></section><?php endif; ?>
<?php if('school'!==$type): if(have_posts()): ?><div class="yl-article-grid"><?php while(have_posts()):the_post(); ?><article class="yl-article-card"><p class="yl-eyebrow"><?php echo esc_html('yl_place'===get_post_type()?'Địa điểm':('yl_event'===get_post_type()?'Sự kiện':'Bài viết')); ?></p><h2><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2><p><?php echo esc_html(wp_trim_words(get_the_excerpt(),26)); ?></p></article><?php endwhile; ?></div><nav class="yl-pagination"><?php the_posts_pagination(); ?></nav><?php elseif(!$school_terms): ?><div class="yl-empty-state"><h2>Chưa tìm thấy chỗ phù hợp</h2><p>Thử từ khóa ngắn hơn, bỏ bớt điều kiện hoặc tìm bằng tên trường như HUBT, HUST, NEU.</p><a class="yl-button yl-button--ghost" href="<?php echo esc_url(get_post_type_archive_link('yl_place')); ?>">Mở Khám phá</a></div><?php endif; endif; ?>
</div></div><?php get_footer(); ?>
