<?php
get_header();
$term=get_queried_object();
$short=function_exists('yl_get_school_meta')?yl_get_school_meta($term,'short_name',$term->name):$term->name;
$address=function_exists('yl_get_school_meta')?yl_get_school_meta($term,'address'):'';
$district=function_exists('yl_get_school_meta')?yl_get_school_meta($term,'district'):'';
$source=function_exists('yl_get_school_meta')?yl_get_school_meta($term,'source_url'):'';
$checked=function_exists('yl_get_school_meta')?yl_get_school_meta($term,'source_checked'):'';
$verified=function_exists('yl_get_school_meta')&&'1'===(string)yl_get_school_meta($term,'verified','0');
$coord_verified=function_exists('yl_get_school_meta')&&'1'===(string)yl_get_school_meta($term,'coord_verified','0');
$lat=function_exists('yl_get_school_meta')?yl_get_school_meta($term,'latitude'):'';
$lng=function_exists('yl_get_school_meta')?yl_get_school_meta($term,'longitude'):'';
$regional_slugs=function_exists('yl_get_school_nearby_district_slugs')?yl_get_school_nearby_district_slugs($term):array();
$school_maps=function_exists('yl_school_maps_url')?yl_school_maps_url($term):'https://www.google.com/maps/search/?api=1&query='.rawurlencode($address?$address:$term->name.', Hà Nội');
$archive_url=get_post_type_archive_link('yl_place');
$direct_query=new WP_Query(array('post_type'=>'yl_place','post_status'=>'publish','posts_per_page'=>12,'tax_query'=>array(array('taxonomy'=>'near_school','field'=>'term_id','terms'=>$term->term_id)),'orderby'=>array('menu_order'=>'ASC','date'=>'DESC'),'no_found_rows'=>true));
$is_regional=false; $display_query=$direct_query;
if(!$direct_query->have_posts()&&$verified&&$regional_slugs){$regional_query=new WP_Query(array('post_type'=>'yl_place','post_status'=>'publish','posts_per_page'=>12,'tax_query'=>array(array('taxonomy'=>'district','field'=>'slug','terms'=>$regional_slugs,'operator'=>'IN')),'orderby'=>array('menu_order'=>'ASC','date'=>'DESC'),'no_found_rows'=>true));if($regional_query->have_posts()){$display_query=$regional_query;$is_regional=true;}}
$region_names=array();foreach($regional_slugs as $regional_slug){$dt=get_term_by('slug',$regional_slug,'district');if($dt&&!is_wp_error($dt))$region_names[]=$dt->name;}$region_names=array_values(array_unique($region_names));
$tabs=array('quan-an'=>'Ăn','cafe'=>'Café','hoc-tap'=>'Học','photocopy'=>'Photocopy','dich-vu'=>'Dịch vụ','vui-choi'=>'Đi chơi');
$markers=array();
if($coord_verified&&is_numeric($lat)&&is_numeric($lng)){foreach($display_query->posts as $place_post){if('1'!==(string)get_post_meta($place_post->ID,'_yl_coord_verified',true))continue;$plat=get_post_meta($place_post->ID,'_yl_latitude',true);$plng=get_post_meta($place_post->ID,'_yl_longitude',true);if(is_numeric($plat)&&is_numeric($plng))$markers[]=array('name'=>get_the_title($place_post),'lat'=>(float)$plat,'lng'=>(float)$plng);}}
$direct_count=(int)$term->count;
?>
<div class="yl-page-shell"><div class="yl-container yl-campus-page yl-campus-page--v724">
<nav class="yl-breadcrumb"><a href="<?php echo esc_url(home_url('/')); ?>">Trang chủ</a><span>/</span><a href="<?php echo esc_url(home_url('/gan-truong/')); ?>">Quanh trường</a><span>/</span><span><?php echo esc_html($short); ?></span></nav>
<header class="yl-campus-page__head yl-campus-page__head--v724"><div><p class="yl-eyebrow">Quanh trường</p><h1><?php echo esc_html('Quanh '.$short.' có gì?'); ?></h1><p class="yl-campus-fullname"><?php echo esc_html($term->name); ?></p><?php if($district||$address): ?><p class="yl-campus-location"><?php echo yl_icon('map'); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?><span><?php echo esc_html($district?$district:$address); ?></span></p><?php endif; ?><p class="yl-campus-summary"><?php echo esc_html($term->description?$term->description:'Những chỗ YangLocal ghi nhận quanh campus để bạn tìm nhanh chỗ ăn, café, học và dịch vụ.'); ?></p><div class="yl-campus-status-line"><span><?php echo $direct_count>0?esc_html(number_format_i18n($direct_count).' địa điểm quanh campus'):($is_regional?'Gợi ý trong khu vực quanh trường':'Đang bổ sung thêm địa điểm'); ?></span></div></div><aside class="yl-campus-meta-card"><strong>Đi tới trường</strong><?php if($address): ?><p><?php echo esc_html($address); ?></p><?php endif; ?><?php if($school_maps): ?><a class="yl-button yl-button--ghost yl-button--compact" href="<?php echo esc_url($school_maps); ?>" target="_blank" rel="noopener noreferrer">Mở vị trí trường</a><?php endif; ?></aside></header>
<section class="yl-campus-browser"><div class="yl-section-heading yl-section-heading--compact"><div><p class="yl-eyebrow">Bạn cần gì?</p><h2>Chọn nhanh quanh trường</h2></div></div><nav class="yl-campus-tabs" aria-label="Nhu cầu quanh trường"><?php foreach($tabs as $slug=>$label): $args=array(); if('photocopy'===$slug){$args=array('category'=>'dich-vu','q'=>'photocopy');}else{$args['category']=$slug;} if($is_regional&&$regional_slugs){$args['district']=$regional_slugs[0];}else{$args['school']=$term->slug;} ?><a href="<?php echo esc_url(add_query_arg($args,$archive_url)); ?>"><?php echo esc_html($label); ?></a><?php endforeach; ?></nav><?php if($is_regional): ?><p class="yl-campus-area-note">Mở rộng sang <?php echo esc_html(implode(', ',$region_names)); ?> để có thêm lựa chọn.</p><?php endif; ?></section>
<?php if($display_query->have_posts()): ?><section class="yl-section yl-section--tight"><div class="yl-section-heading yl-section-heading--compact"><div><p class="yl-eyebrow">Đi nhanh quanh trường</p><h2>Một vài chỗ đáng xem trước</h2></div><a class="yl-section-link" href="<?php echo esc_url(add_query_arg($is_regional&&$regional_slugs?array('district'=>$regional_slugs[0]):array('school'=>$term->slug),$archive_url)); ?>">Xem tất cả →</a></div><div class="yl-campus-guide-layout"><div class="yl-campus-guide-list"><div class="yl-place-grid yl-place-grid--campus"><?php $shown=0;while($display_query->have_posts()&&$shown<6):$display_query->the_post();get_template_part('template-parts/place-card');$shown++;endwhile; ?></div><?php wp_reset_postdata(); ?></div><?php if($coord_verified&&is_numeric($lat)&&is_numeric($lng)): ?><aside class="yl-campus-guide-map"><div class="yl-campus-map" data-yl-campus-map data-lat="<?php echo esc_attr($lat); ?>" data-lng="<?php echo esc_attr($lng); ?>" data-name="<?php echo esc_attr($short); ?>"><script type="application/json"><?php echo wp_json_encode($markers); ?></script></div><div class="yl-map-fallback yl-map-fallback--compact" data-yl-map-fallback hidden><p>Không tải được nền bản đồ. Bạn vẫn có thể mở bản đồ lớn.</p></div><a class="yl-text-link" href="<?php echo esc_url($school_maps); ?>" target="_blank" rel="noopener noreferrer">Mở bản đồ lớn ↗</a></aside><?php endif; ?></div></section>
<?php else: ?><div class="yl-empty-state"><h2>Chưa tìm thấy chỗ phù hợp</h2><p>Thử mở Khám phá và chọn khu vực gần trường để xem thêm địa điểm.</p><a class="yl-button yl-button--ghost" href="<?php echo esc_url($archive_url); ?>">Mở Khám phá</a></div><?php endif; ?>
<?php if($source): ?><details class="yl-campus-source yl-provenance"><summary>Nguồn & cập nhật</summary><p><a href="<?php echo esc_url($source); ?>" target="_blank" rel="noopener noreferrer">Mở nguồn campus</a><?php if($checked): ?> · cập nhật <?php echo esc_html(date_i18n('d/m/Y',strtotime($checked))); ?><?php endif; ?></p></details><?php endif; ?>
</div></div><?php get_footer(); ?>
